#默认使用配置
#spring:
#  profiles:
#    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.bysj_1.dao
  mapperLocations: classpath:mapper/*.xml


#开发配置
spring:
#  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bysj?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 000000
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
   # mode: LEGACYHTML5
    mode: HTML5
    cache: false #关闭缓存，可查看实时页面
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 8090